apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231022031353.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231022031353.0.0+build.02e9424
  releaseNotes: |
    Release v20231022031353.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-21-10-2023-23-23-02-880829566/where-for-dinner-my-apps-bundle@sha256:fcde655b034236bdd197d70878653da219da90f8fadc29b797e2ee8949e6dfd2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

